baseURL = 'https://aldofusterturpin.github.io/blog/'
languageCode = 'en-us'
title = 'SOLID Engineer'
theme = "tale"
[Author]
    name = "Aldo Fuster Turpin"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About me"
    title = "About mes"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[params]
  css = ["css/styles.css"]